### ISSUE TITLE
Does ansible-lint include a check for the new FQCNs?

### ISSUE THREAD

**Issue by loganmarchione** [ansible-community/ansible-lint#1061]
##### Summary
As the title says, does ansible-lint include a check to replace all my old module names with the new [FQCNs](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#using-collections-in-a-playbook)?

I know I can use `-vv` when I actually run the playbook, but if there was an ansible-lint check, that would be easier.

##### Issue Type

- Feature Idea

##### Additional Information

N/A

**Comment by mdlopresti** [comment]
This would be nice for integrating a check into CI too
