### ISSUE TITLE
'Deprecated rules' should be renamed 'Deprecation rules' to avoid confusion

### ISSUE THREAD

**Issue by jdrowne** [ansible-community/ansible-lint#1106]
##### SUMMARY

The documentation refers to the 1xx rules as "Deprecated rules" but this can be misinterpreted as "rules that have been deprecated". To avoid confusion, they should be called "Deprecation rules" instead or something similar.

**Comment by ssbarnea** [comment]
@jdrowne Sure, file a PR! That one was likely easier to fix with a PR then adding mew bug :D

**Comment by netzvieh** [comment]
Hi, not sure if this would be just a docs change. I think the most confusing part in the README for this case would be the table containing the tags + rules. If we change that we have to change the tag to deprecation. That's a code change in the default rules, and probably for users aswell if they use custom rules or skip "deprecated" rules via skip_list.

**Comment by ssbarnea** [comment]
Considering that master already contains major/breaking changes, I would support correcting this historical mistake and replacing the misleading `deprecated` tag with `deprecation` or `deprecations` (not sure which one is better).

We can assure this will be part of the release notes and user will know to update their config file if they already disabled this rule.

**Comment by ssbarnea** [comment]
I would also remove the old `ANSIBLE00...` tags but as a separated change. Feel free to raise them.
