### ISSUE TITLE
Rule 202 (Octal file permissions must contain leading zero or be a string) find an error in mode: 0756

### ISSUE THREAD

**Issue by kazh000** [ansible-community/ansible-lint#1237]
##### Summary

Linter finds an error of the rule 202 in mode: 0756

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible 2.10.4
config file = None
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.6.12 (default, Dec 18 2020, 06:04:50) [GCC 8.3.0]

ansible-lint 5.0.0a1.dev8
```

- ansible installation method: one of source, pip, OS package
- ansible-lint installation method: one of source, pip, OS package

##### OS / ENVIRONMENT

Run in docker. Dockerfile:
```
FROM python:3.6

WORKDIR /usr/src/app

RUN pip install git+https://github.com/ansible-community/ansible-lint "ansible"

RUN ansible   --version

RUN ansible-lint --version

RUN echo "---\n- hosts: localhost\n  gather_facts: no\n  tasks:\n\
  - name: Reproduce the bug in the rule 202\n    file:\n\
      path: /tmp/test_file\n      mode: 0756\n      state: touch" > test.yml

RUN cat test.yml

RUN ansible-playbook --syntax-check test.yml

RUN ansible-lint --force-color --show-relpath test.yml
```
##### STEPS TO REPRODUCE

```console (paste below)
docker build --rm -f Dockerfile .
```

##### Desired Behaviour

No error message

##### Actual Behaviour

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:
- playbook
- output of running ansible-lint
- if you're getting a stack trace, output of
  `ansible-playbook --syntax-check playbook`

```paste below
Step 1/9 : FROM python:3.6
 ---> bd4a91d81d7e
Step 2/9 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 6b223c53a8f1
Step 3/9 : RUN pip install git+https://github.com/ansible-community/ansible-lint "ansible"
 ---> Using cache
 ---> 6af3b1194721
Step 4/9 : RUN ansible   --version
 ---> Running in 3bbecc9be4ea
ansible 2.10.4
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.12 (default, Dec 18 2020, 06:04:50) [GCC 8.3.0]
Removing intermediate container 3bbecc9be4ea
 ---> 5b5d3318ca93
Step 5/9 : RUN ansible-lint --version
 ---> Running in a3d017cc77eb
ansible-lint 5.0.0a1.dev8
Removing intermediate container a3d017cc77eb
 ---> f555ba7baf02
Step 6/9 : RUN echo "---\n- hosts: localhost\n  gather_facts: no\n  tasks:\n  - name: Reproduce the bug in the rule 202\n    file:\n      path: /tmp/test_file\n      mode: 0756\n      state: touch" > test.yml
 ---> Running in 8215c2cd060f
Removing intermediate container 8215c2cd060f
 ---> c9d43ba87a60
Step 7/9 : RUN cat test.yml
 ---> Running in 3cf924df406e
---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Reproduce the bug in the rule 202
    file:
      path: /tmp/test_file
      mode: 0756
      state: touch
Removing intermediate container 3cf924df406e
 ---> 5657809c2ca7
Step 8/9 : RUN ansible-playbook --syntax-check test.yml
 ---> Running in 0ca2a8bc68aa
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
playbook: test.yml
Removing intermediate container 0ca2a8bc68aa
 ---> 8e6f8f41bf37
Step 9/9 : RUN ansible-lint --force-color --show-relpath test.yml
 ---> Running in d8faa37f8046
WARNING  Listing 1 violation(s) that are fatal
202: Octal file permissions must contain leading zero or be a string
test.yml:5 Task/Handler: Reproduce the bug in the rule 202
You can skip specific rules or tags by adding them to your configuration file:
# .ansible-lint
warn_list:  # or 'skip_list' to silence them completely
  - '202'  # Octal file permissions must contain leading zero or be a string
Finished with 1 failure(s), 0 warning(s) on 1 files.
The command '/bin/sh -c ansible-lint --force-color --show-relpath test.yml' returned a non-zero code: 2
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by ssbarnea** [comment]
You did not read the full error message, you should use the recommended format to avoid confusions, the one supported by YAML 1.2, which is also recognized by ansible. 

It is true that Ansible docs file file mode do not mention the best way to include octals, but that is not a bug of the linter.

**Comment by nradchenko** [comment]
Well, the error says `Octal file permissions must contain leading zero or be a string`, and `mode: 0756` seems to meet this condition because the value starts with a zero. But curiously, this particular test playbook check does not fail if you replace `0756` with `0755` or `0750` leaving the rest of the file unchanged.

Inspecting source code shows that `OctalPermissionsRule` checks whether the permissions are "sensible" and triggers an error if they aren't.

https://github.com/ansible-community/ansible-lint/blob/bedcb8d78c1543cf920a8907b53631113fac3583/src/ansiblelint/rules/OctalPermissionsRule.py#L50-L81

Obviously, `other_more_generous_than_group` is true for `0756`, so the test fails.

This additional check is confusing because neither error message nor documentation mention it, and one could not probably understand the error cause without looking at the sources. I think that having more verbose error messages there would be great! @ssbarnea

**Comment by ssbarnea** [comment]
Please make a pull request with the extra docs improvement, I will include it in next patch release.
