### ISSUE TITLE
German "umlaut" causes "Unable to determine file type for..."

### ISSUE THREAD

**Issue by phihos** [ansible-community/ansible-lint#1339]
##### Summary

When a filename contains a German umlaut like `äöü` `ansible-lint` crashes with
```
Unable to determine file type for "playbook-with-umlaut-\303\274.yml"
```
Note that the `ü` in this case get escaped to `\303\274`.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible --version

ansible 2.9.13
  config file = ...
  configured module search path = ['...']
  ansible python module location = ...
  executable location = ...
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]


ansible-lint --version

ansible-lint 5.0.0
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

Create a playbook `playbook-with-umlaut-ü.yml`. Run `ansible-lint`.

##### Desired Behaviour

`ansible-lint` should not crash.

##### Actual Behaviour

`ansible-lint`  crashes with:
```
Unable to determine file type for "playbook-with-umlaut-\303\274.yml"
```

(PR is already prepared and will be opened within the next 5 mins)

**Comment by ssbarnea** [comment]
Closed by #1340
