### ISSUE TITLE
ansible-lint returing an exit code of 1 on success

### ISSUE THREAD

**Issue by joej164** [ansible-community/ansible-lint#1343]
##### Summary
Ansible-lint returning exit code 1 on success.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
(venv) [ignw@server devnet_lab_discovery]$ ansible --version
ansible 2.10.2
  config file = /home/ignw/repos/devnet_lab_discovery/ansible.cfg
  configured module search path = ['/home/ignw/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ignw/repos/devnet_lab_discovery/venv/lib/python3.8/site-packages/ansible
  executable location = /home/ignw/repos/devnet_lab_discovery/venv/bin/ansible
  python version = 3.8.5 (default, Sep  1 2020, 11:03:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
(venv) [ignw@server devnet_lab_discovery]$ ansible-lint --version
ansible-lint 5.0.0
(venv) [ignw@server devnet_lab_discovery]$ 

```

- ansible installation method: pip install ansible
- ansible-lint installation method: pip install "ansible-lint[yamllint]"

##### OS / ENVIRONMENT

Centos 7

##### STEPS TO REPRODUCE

```console (paste below)
(venv) [ignw@server devnet_lab_discovery]$ ansible-lint -vvvvv
DEBUG    Logging initialized to level 10
DEBUG    Options: Namespace(colored=True, config_file=None, cwd=PosixPath('/home/ignw/repos/devnet_lab_discovery'), display_relative_path=True, exclude_paths=[], format='rich', kinds=[{'requirements': 'requirements.yml'}, {'requirements': '**/meta/requirements.yml'}, {'reno': 'releasenotes/*/*.{yaml,yml}'}, {'playbook': '**/playbooks/*.{yml,yaml}'}, {'playbook': '**/*playbook*.{yml,yaml}'}, {'role': '**/roles/*/'}, {'tasks': '**/tasks/*.{yaml,yml}'}, {'handlers': '**/handlers/*.{yaml,yml}'}, {'vars': '**/{vars,defaults}/*.{yaml,yml}'}, {'meta': '**/meta/main.{yaml,yml}'}, {'yaml': '.config/molecule/config.{yaml,yml}'}, {'yaml': '**/molecule/*/molecule.{yaml,yml}'}, {'playbook': '**/molecule/*/*.{yaml,yml}'}, {'yaml': '**/*.{yaml,yml}'}, {'yaml': '**/.*.{yaml,yml}'}], lintables=[], listrules=False, listtags=False, loop_var_prefix=None, mock_modules=[], mock_roles=[], offline=None, parseable=False, parseable_severity=False, progressive=False, quiet=False, rulesdir=[], rulesdirs=['/home/ignw/repos/devnet_lab_discovery/venv/lib/python3.8/site-packages/ansiblelint/rules'], skip_list=[], tags=[], use_default_rules=False, verbosity=5, version=False, warn_list=['experimental'])
Running ansible-galaxy install --roles-path .cache/roles -vr requirements.yml
Running ansible-galaxy collection install -p .cache/collections -vr requirements.yml
(venv) [ignw@server devnet_lab_discovery]$ echo $?
1
```

##### Desired Behaviour

I expected ansible-lint to succeed with an exit code of 0.  

Possible security bugs should be reported via email to `security@ansible.com`

##### Actual Behaviour

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:
I'm running ansible-lint in my CICD pipeline.  Version 5.0.0 just released.  Now my pipeline is failing, but i get no output with regards to why i'm getting a 1 as my exit code.

```paste below

```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by joej164** [comment]
uninstalling and reinstalling version 4.3.7 my code passes with no issue.

**Comment by ssbarnea** [comment]
Are you sure you did not hide the stderr from your example?

Exit code is likely caused by failure from galaxy install command above. Run it separately and see if that works.

Also include a link to a repo where this can be reproduced.

**Comment by robertdebock** [comment]
I see the same issue:

```shell
$ cd ansible-role-example
$ ansible-lint 
Running ansible-galaxy install --roles-path .cache/roles -vr requirements.yml
$ echo $?
1
```

You can see the [results](https://github.com/robertdebock/ansible-role-locale/runs/1894630177?check_suite_focus=true) and the [code](https://github.com/robertdebock/ansible-role-locale/tree/bf9ed356422fb622f1b461c956b46fb316cd0841).

Please let me know if I can do something to help out, I love Ansible Lint, which is [always right](https://robertdebock.nl/presentations/perfect-ansible/#/5/4)!

**Comment by joej164** [comment]
The repo I'm working in is Private.  I'll try what you said above, I'll also, if I get time this weekend, see if I can replicate in a Vagrant environment for testing purposes and put that in a repo.

Also, to echo @robertdebock comment, would be nice if it would show that with the -v or -vvvvv option set.

**Comment by joej164** [comment]
was able to duplicate it in a public repo.  i'll post it shortly, but I have a `requirements.yml` file in the base of my repo.  When that is present, things blow up

**Comment by joej164** [comment]
https://github.com/joej164/ansible-lint-bug

the readme has all the info and screen shots.  the vagrant file allow you to replicate this locally.

**Comment by ssbarnea** [comment]
You bug is caused by the use of old v1 requirements.yml format documented at https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file -- upgrade it, and it will not fail.

There is work in progress to add schema validation at https://github.com/ansible-community/ansible-lint/pull/1359 but there are no plans to use already deprecated old format.

Please read https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file 

As opposed to Ansible itself, the linter focused on current formats and does not aim to support deprecated formats. Main reason for that is that lack of volunteers for maintaining such features.

**Comment by joej164** [comment]
ok, thanks for letting me know what the issue was.  no need to support old formats but hopefully the schema validation will provide better error messages when that issue occurs for other people.
