### ISSUE TITLE
.yamllint file in root directory is not used when ansible-lint runs yamllint

### ISSUE THREAD

**Issue by geerlingguy** [ansible-community/ansible-lint#1344]
##### Summary

See background: https://github.com/ansible-community/ansible-lint/discussions/1150#discussioncomment-367068

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

Latest from pip.

##### OS / ENVIRONMENT

Ubuntu 20.04, GitHub Actions CI

##### STEPS TO REPRODUCE

TODO: I'll be posting this shortly.

##### Desired Behaviour

TODO.

##### Actual Behaviour

TODO.

**Comment by felixfontein** [comment]
That's interesting, because ansible-lint *does* seem to find your .yamllint config: `Loading custom .yamllint config file, this extends our internal yamllint config.`

**Comment by felixfontein** [comment]
I created a fix for the actual problem (`ignore` not used) in #1346.
