### ISSUE TITLE
ansible-lint reinstall collections that are already there

### ISSUE THREAD

**Issue by xenlo** [ansible-community/ansible-lint#1364]
##### Summary
Ansible-lint reinstall all collections into `.cache/collections/` even all collections where already installed in the environment.

This is not consistent with the behavior of `ansible-playbook` or `ansible-galaxy`.

##### Issue Type
- Bug Report

##### Ansible and Ansible Lint details
```
xenlo $ ansible --version
ansible 2.9.17
  config file = /home/xenlo/Projects/543/etc/ansible.cfg
  configured module search path = ['/home/xenlo/Projects/543/library']
  ansible python module location = /home/xenlo/.virtualenvs/543/lib/python3.9/site-packages/ansible
  executable location = /home/xenlo/.virtualenvs/543/bin/ansible
  python version = 3.9.1 (default, Jan 20 2021, 00:00:00) [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]

xenlo $ ansible-lint --version
ansible-lint 5.0.0
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT
Fedora 33

##### STEPS TO REPRODUCE
1. Create a `requirement.yml` file in your project.
2. Fill it with some collections
    ```yml
    ---
    collections:
      - community.vmware
    ```
3. Install the collections
    ```
    ansible-galaxy collection install -r requirements.yml
    ```
4. Ensure that you don't have cache already
    ```
    rm -rf .cache/collections/
    ```
5. Run `ansible-lint`
6. Check what ansible-lint installed
    ```
    $ ls -l .cache/collections/ansible_collections/
    total 4
    drwxrwxr-x. 3 xenlo xenlo 4096 17 fév 12:48 community
    ```

##### Desired Behaviour
When we run `ansible-lint`, it first checks in the collections path (the default or the one define in ansible.cfg) if the collection is already present. And only if not, it install under `.cache/` directory.

##### Actual Behaviour
Ansible-lint don't care about what is already present and re-install all collections in `.cache/collections/`.

```
xenlo $ cat requirements.yml
---
collections:
  - community.vmware

xenlo $ ansible-galaxy collection install -r requirements.yml
[WARNING]: Collection at '/home/xenlo/.ansible/collections/ansible_collections/ansible/windows' does not have a MANIFEST.json file, cannot detect version.
Process install dependency map
Starting collection install process
Skipping 'community.vmware' as it is already installed

xenlo $ rm -rf .cache/
xenlo $ ansible-lint
Running ansible-galaxy install --roles-path .cache/roles -vr requirements.yml
Running ansible-galaxy collection install -p .cache/collections -vr requirements.yml
Added ANSIBLE_COLLECTIONS_PATHS=.cache/collections
Added ANSIBLE_ROLES_PATH=/home/ahgff/Projects/543/roles.galaxy:/home/ahgff/Projects/543/roles:roles
INFO     Discovering files to lint: git ls-files *.yaml *.yml
INFO     Discovering files to lint: git ls-files *.yaml *.yml
INFO     Executing syntax check on playbooks/deploy_base_server.yml (1.97s)
[…]
```

**Comment by ssbarnea** [comment]
That is not a bug of ansible-lint, is a missing feature of ansible-galaxy and you should raise it with them.  If we would not call galaxy install again, we would risk of not installing changed deps.

Note theat galaxy also has a force flag, which we do not use, so from our point of view, we do not reinstall collections.

If that bothers you a lot, you can instead mock these collections instead of installing them and enable offline mode, so the linter will not attempt to install anything.

**Comment by xenlo** [comment]
Thanks for your answer.
Can you confirm that I understand correctly (not sure at all :worried:) :
- Running ansible-lint with the existing collections and only installing in .cache those which could miss, is not an option?
- Having in ansible-galaxy the posiblity to install in a given location (let say .cache) the collections that are missing or not up-to-date in paths of ansible environment, would be a helpful feature?

It's not a big deal for us. Actually our scripts ensure that our work environments and the CI has everything they need before running lint tests. So the --offline will for us.

Nevertheless, I can push a feature request to ansible-galaxy if it helps.
