### ISSUE TITLE
ansible-lint should be able to query ansible config

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#1375]
##### Summary
Originally identified in https://github.com/ansible-community/ansible-lint/issues/1354 this feature request is tracking ability to load important ansible config items like role/libary/module/collection paths.

**Comment by pgassmann** [comment]
@ssbarnea Thank you for pointing me to this issue. Can you quickly explain why you name it a feature request? This worked with the releases before 5.0.0.

What changed with 5.0.0 that affects this functionality? is it related to the automatic download of collections and roles?

In my opinion, ansible-lint should default to the offline mode and use the same config as ansible, without download-magic, so it checks what ansible is using when running playbooks.

**Comment by ssbarnea** [comment]
What you say is not really true: ansible-lint by itself does nothing special to prevent ansible from loading the config. In fact ansible is still loading the config even when called from within ansiblelint.

The current behaviour is caused by a side-effect of how ansible behavior when it encounters ANSIBLE_* vars. Practically any config item defined as an environment variable does disable the loading of that item from ansible.cfg (overriding it). As the linter may need to extend one or more of these vars, a side effect is that this shadows the values customized inside you ansible.cfg. Those that did not customize these values are not affected, only those that already had custom values inside.

As I said, a patch that would address this would be welcomed.

**Comment by ssbarnea** [comment]
Since v6 we already doing this.
