### ISSUE TITLE
Rule unnamed-task should not have any exceptions

### ISSUE THREAD

**Issue by ansiblejunky** [ansible-community/ansible-lint#1411]
##### Summary

Ansible good practice generally states to [name all your tasks](https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#always-name-tasks). A simple straightforward rule that should always be applied. Having exceptions to this rule breaks the general philosophy around maintaining good practice. Additionally, [ansible-lint docs](https://ansible-lint.readthedocs.io/en/latest/default_rules.html#unnamed-task) never state the exceptions at all for this rule. However in the Python code we can see [there are indeed exceptions](https://github.com/ansible-community/ansible-lint/blob/ed24aa6d75d894f121a36b96792f03009990940f/src/ansiblelint/rules/TaskHasNameRule.py#L37-L44) that are not enforced.

```
    _nameless_tasks = [
        'meta',
        'debug',
        'include_role',
        'import_role',
        'include_tasks',
        'import_tasks',
    ]
```

While there can be a debate around naming these modules in the exceptions, it generally is a much better practice to have a simple rule that is always applied versus having exceptions to the rule especially when they are not truly documented anywhere.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible --version
latest
ansible-lint --version
latest
```

- ansible installation method: source
- ansible-lint installation method: source

##### OS / ENVIRONMENT

any

##### STEPS TO REPRODUCE

Run ansible-lint against playbook containing unnamed tasks using any of the module exceptions (debug, meta, etc.).

##### Desired Behaviour

ansible-lint should not have exceptions to this rule and should enforce naming of all tasks

##### Actual Behaviour

ansible-lint does not complain when unnamed tasks use the modules listed in the python code as exceptions

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by tonykay** [comment]
I agree strongly, the idea that certain tasks, hidden in the code of the linter, have an exempt status is to me confusing and echo @ansiblejunky's comment  _A simple straightforward rule that should always be applied_

**Comment by ssbarnea** [comment]
These exceptions are historical and very old and I do also agree with OP as we should have no exceptions.

Please make a pull-request to remove them, I will support it. I will only need to wait a little bit more before releasing it as it will annoy few users.

I do remember having long-debates with some colleagues in the past which seen the naming of the tasks useless. Some things changed and did not hear the the same comment for very long time.

Personally I would even look to have a test for no-dup-task-name, as this is another common mistake around naming which makes debugging hard, as you have no idea which task produced it.
