### ISSUE TITLE
for asible-lint to used in windows（Especially in VScode), please do not get ansible version by subprocess

### ISSUE THREAD

**Issue by yoke88** [ansible-community/ansible-lint#1495]
https://github.com/ansible-community/ansible-lint/blob/facedd97e4efba718b71a272177f6bd741cd9cfc/src/ansiblelint/config.py#L130-L137

**Comment by ssbarnea** [comment]
Probable you do not realise that ansible needs to be installed and working for the linter to work. It will call ansible both as a subprocess and even import some code during the run. Even if you disabled this check, it will fail later.

To be clear: https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-ansible-run-on-windows -- Windows is not supported by Ansible itself, so neither by the linter.
