### ISSUE TITLE
5.0.7 release broke archlinux packaging due to adding tenacity dependency

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#1523]
##### Summary
Adding tenacity in 5.0.7 did broke arch packaging: https://bugs.archlinux.org/task/70365

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT
arch

Possible remediations
* downstream packaging to add tenacity
* replace use of tenacity with internal retry implementation (our use of retry is simple, should not hard)
* add a pipeline (gha) to test that arch packaging does not get broken by change in linter deps.

**Comment by aminvakil** [comment]
Something like this would do the work for arch:
https://github.com/aminvakil/aur/blob/master/.github/workflows/ci.yml#L25-L70

**Comment by Scimmia22** [comment]
Arch already builds all packages in an nspawn container, so no, going to docker won't do anything.

**Comment by ssbarnea** [comment]
@aminvakil @Scimmia22 I created a new branch https://github.com/ansible-community/ansible-lint/tree/feat/pkg for adding arch package building directly here. Feel free to contribute to it.

What I would like to see is a simple script in `tools/pkg-arch.sh` that verifies that we can build and install an arch package, using a container, so anyone can run it locally, regardless from which (Linux) OS is calling the script.

**Comment by freswa** [comment]
One of the Arch maintainer here. I wonder why the minor version wasn't bumped when minor changes got introduced in the 5.0.7 release? I'm down for automatic tests, but I don't think that would fix the dependency issue I introduced in the package.
Couldn't we agree on introducing dependency changes only if also minor or major version is bumped too?

**Comment by ssbarnea** [comment]
I agree agree that that this should have being versioned as 5.1.0 for this reason, it is too late to undo it now. I can clearly try double check that in the future.

Still here is another thing to consider: bumping even a dependency version requirement could potentially create some packaging issue for arch or others. I am saying this due to the sideeffects I seen from cryptography python library switching to rust. Clearly something like this would count as a patch security update, and still likely to break.

Based on my experience the only thing that is very unlikely to break is what is tested with CI before being merged. Anything else is a more or less of a gamble.
