### ISSUE TITLE
prerun should set ANSIBLE_CONFIG when ansible.cfg is found in repository root

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#1586]
##### Summary

As ansible default behavior is to load ansible.cfg from current directory it means that when running from a subfolder, that same config file will not be loaded and ansible will default to the user home directory config. When writing code and using tools like ansible-lint or molecule, this is unlikely to be desired behavior, as the develop would expect that the repo level ansible.cfg will affect anything is run inside it.

##### Issue Type

- Bug Report

##### Desired Behaviour

We should set `ANSIBLE_CONFIG=/path-to-repo/ansible.cfg` when the variable is not already defined and the file is present. This will assure that regardless from which subdirectory you run ansible, it will still use the in-repo configuration.

This feature is quite easy to fix and presents a major advantage for molecule, where scenarios found deeper level (inside collection roles) would gain access to ansible config. Feedback is welcomed in this proposed behavior change.

/polls Option1 'Option 2' "Option 3"

**Comment by tadeboro** [comment]
Since Molecule does not specify how Ansible is run, I would see this new behavior as unexpected. And since we already have a way of forcing the right config usage, I would vote for documenting how to customize Ansible configuration through environment variables and call it a day.
