### ISSUE TITLE
ansible-lint apk package not supported anymore ?

### ISSUE THREAD

**Issue by nvuillam** [ansible-community/ansible-lint#1644]
##### Summary

Since latest alpine linux package, ansible-lint does not appear anymore, is it on purpose ?

Thanks

**Comment by aminvakil** [comment]
I'd think you'd better be asking alpine devs about this :)
But yeah, it's not in 3.14 (yet?).
https://pkgs.alpinelinux.org/packages?name=ansible-lint&branch=v3.13
https://pkgs.alpinelinux.org/packages?name=ansible-lint&branch=v3.14

**Comment by ssbarnea** [comment]
No distro packaging was ever supported for the linter but if a distro maintainer wants to propose some CI pipelines that assure building the packages work and even publishing them, I will be happy to review them.

**Comment by smcavoy** [comment]
@nvuillam regarding Alpine Linux packaging of ansible-lint, release 3.15 of Alpine Linux [includes](https://pkgs.alpinelinux.org/packages?name=ansible-lint&branch=v3.15) ansible-lint 4.3.7

There is an open [request](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/29452) to include version 5.3.2 in the edge release of Alpine Linux.

This means at least version 5.3.2 of ansible-lint will be included in the next stable release of Alpine Linux and most likely whatever the current ansible-lint release is just before the package freeze before the next stable release.

**Comment by ssbarnea** [comment]
@smcavoy If there is anything we can help with lets me know. For example, if you want to add a job that ensures that current code can be packaged as apk we are more than open to accept it. We already have an open PR to add rpm packaging testing directly on this repo, so we will prevent making changes that would break downstream packaging.
