### ISSUE TITLE
Add a packaging extra for pulling `ansible-core`

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-lint#1717]
# Issue Type
- Feature request

# Desired Behaviour

There's extras in `setup.cfg` that depend on `ansible` and `ansible-base`. We need a similar one for `ansible-core`.

**Comment by ssbarnea** [comment]
I think that is a bugfix and we should just fix it at https://github.com/ansible-community/ansible-lint/blob/main/setup.cfg#L97-L98

Basically we will not have an extra for 2.10, but if someone needs 2.10 in particular they can install it without an extra. 

Just replace ansible-base with ansible-core and we can call this fixed.
