### ISSUE TITLE
yamllint soft-dependency should be removed

### ISSUE THREAD

**Issue by jamesquilty** [ansible-community/ansible-lint#1735]
##### Summary

#953 introduced a "soft-dependency" on yamllint. While that was a well-intentioned decision, it also very unfortunately created a situation where the behaviour of the linter is unpredictable and unreliable: it depends on whether the yamllint library can be found (not _present_ but _found_, see: #1722). This particularly affects teams because ansible-lint is run in a variety of environments and ansible-lint will lint YAML in only _some_ of the environments depending on whether it can find the yamllint library. It's a pernicious situation because the absence of the library is indistinguishable from the absence of yaml lint rule violations.

This issue requests the removal of the "soft-dependency" to improve linter predictability and reliability.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

Not relevant (but, see #1722).

##### OS / ENVIRONMENT

All.

##### STEPS TO REPRODUCE

1. run `ansible-lint` and observe no rule violation messages
1. Note that this situation is consistent with either:
    1. yaml files being linted and no rule violations being present, _or_
    2. yaml files _not_ being linted.

##### Desired Behaviour

ansible-lint doesn't lint YAML; run yamllint to lint YAML.

##### Actual Behaviour

ansible-lint _sometimes_ lints YAML, depending on the environment in which it is run.

In a recent case in my organisation more than 30 engineers, running macOS, Windows and Linux, attempted to use ansible-lint to enjoy the benefits of standardisation. Some of the development environments are maintained by a sysadmin, so they have limited control of environment configuration. ansible-lint behaved differently in the different environments and it was rather unfair to everyone when code was committed to the repos which contained yaml linting rule violations that the authors - through no fault of their own - were never shown.

I can understand the good intention behind attempting to retain the feature that ansible-lint checks yaml even after yamllint was removed, but the "soft-dependency" has introduced harmful unpredictability into the linter's behaviour for limited benefit. If you want ansible-lint to lint YAML then you have to install yamllint... but in that case you can independently run yamllint on your playbooks at marginal extra cost and with some benefit from additional output and more control over options and configuration.

As I wrote over in #1722,  ansible-lint should either _always_ lint YAML or _never_ lint YAML; it should never _sometimes_ lint YAML depending on the environment in which its run due to the problems this causes. If, as was indicated in https://github.com/ansible-community/ansible-lint/issues/1722#issuecomment-931459419, ansible-lint can not _always_ lint YAML then the desired behaviour should be that it _never_ lints YAML.

**Comment by jamesquilty** [comment]
#1777 reports more confusing behaviour attributable to the inclusion of YAML linting via "soft" integration of yamllint into ansible-lint. I agree that linting of YAML files is related to ansible-lint's core purpose of linting Ansible playbooks. It seems to me that the attempted integration of yamllint is costing more in problems than any benefits it confers: integration complicates the ansible-lint code and creates confusing situations where configurations and environment have non-local effects.

I appreciate the value YAML linting adds to ansible-lint, and globally, so much so that I installed yamllint independently.

The benefits to removing YAML linting are improvements to the simplicity and locality of ansible-lint's core function _and_ licensing, and users can be directed to yamllint as a highly recommended YAML linting tool which complements and enhances ansible-lint.

What would be the costs of making ansible-lint _never_ lint YAML?

**Comment by ssbarnea** [comment]
Shortly, yamllint integration will not go away. We will talk with the team and decide if we are to make yamllint a default dependency, resolving at least one side of the problem. Either way, you will have to add option to skip yaml checks if you do not care about these.

**Comment by ssbarnea** [comment]
@ansible-community/devtools We need to discuss this in next team meeting, mostly related to GPL licensing. I am in favour of making yamllint a permanent dependency and marking distribution of ansible-lint GPL (while keeping its source-code MIT).

Feel free to up/downvote that proposal if you already have an oppinion.
