### ISSUE TITLE
 Vendor enrich library to reduce packaging dependency

### ISSUE THREAD

**Issue by ganeshrn** [ansible-community/ansible-lint#1781]
##### Summary

 Vendor enrich library to reduce packaging dependency https://pypi.org/project/enrich/
Based on the usability research viability to move it to [ansible-compat](https://github.com/ansible-community/ansible-compat) library 

##### Issue Type

- Feature Request
- Research

##### OS / ENVIRONMENT

RPM-based downstreams

##### Desired Behaviour

An unpackaged downstream dependency shouldn't get in the way of packaging our project for that ecosystem.

##### Actual Behaviour

In order to package our project, it is also necessary to package extra projects like enrich that are our dependencies.

**Comment by webknjaz** [comment]
Sorin and I talked about the vendoring strategies the other day. So let me document a few I know of:
1) Implement the same ansible-core has: https://github.com/ansible/ansible/tree/97ef1d0/lib/ansible/_vendor. TL;DR they have an empty directory within the repository that is auto-added to the Python import path and if downstream packagers have problems with packaging the dependencies from PyPI separately, they could drop in those right in this directory and it'll work magically without forcing them to also package those deps.
2) Implement what pip does: https://github.com/pypa/pip/tree/main/src/pip/_vendor#automatic-vendoring. TL;DR they have the vendored deps committed in the repository but the content of the vendor folder is managed automatically using the https://pypi.org/p/vendoring package.
3) Implement what setuptools does: https://github.com/pypa/setuptools/issues/2825 / https://github.com/pypa/setuptools/pull/2764. TL;DR there's efforts to stop/minimize special-casing of the deps as much as possible and let downstreams do their thing. Where not possible, they'll try to use the `vendoring` package made by the `pip` maintainers. This option is mostly about not caring on the upstream side and solving the problem within the spec file.

**Comment by ssbarnea** [comment]
No need to do it, there are rpms for it.
