### ISSUE TITLE
[TODO] Fix the `eco` job

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-lint#1789]
This job has been failing for a while now. Sorin and I have known about it for weeks but never got to fix it. I just realized that there's no tracking issue so I'm filing this one for that purpose.
I'll mark it as non-voting for now (https://github.com/ansible-community/ansible-lint/pull/1790) but the real fix would be to figure out what's going on and address that.

Action items:
* [x] troubleshoot the `eco` job failures and make it pass
* [ ] make the `eco` job voting again

**Comment by ssbarnea** [comment]
@webknjaz I fixed eco job last year. Please undo the change that made it optional. Usually we can fix it in less than a day when it gets broken as all repository maintainers involved are really happy to improve their code.
