### ISSUE TITLE
pre-commit: ansible-lint lints complete repo instead of staged files only

### ISSUE THREAD

**Issue by MAC-R0ch3** [ansible-community/ansible-lint#1957]
##### Summary

ansible-lint executed via pre-commit runs on all files - always

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible --version

ansible [core 2.12.2]
  config file = /home/users/chmielem/.ansible.cfg
  configured module search path = ['/home/users/userid/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/users/userid/dev/venv/python310/lib/python3.10/site-packages/ansible
  ansible collection location = /home/users/userid/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/users/userid/dev/venv/python310/bin/ansible
  python version = 3.10.2 (main, Jan 15 2022, 18:02:07) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True

ansible-lint --version

ansible-lint 5.4.0 using ansible 2.12.2
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

```console
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

uname -r
5.14.0-1024-oem
```

##### STEPS TO REPRODUCE

ansible-lint is configured to run on the pre-commit stage via the pre-commit framework. The .pre-commit-config.yaml has the following config related to ansible-lint.

```console
  [...]
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v5.3.2
    hooks:
      - id: ansible-lint
        name: Executing ansible-lint
        files: example|playbooks|roles
        types: [file]
        stages: [commit]
        additional_dependencies:
          - ansible-core
          - yamllint
    [...]
```

Everytime I am committing, ansible-lint will run on all yml / yaml files, not just the staged ones.

```console
git commit -m "My commit"
```

##### Desired Behavior

ansible-lint should run only on staged files considering relevant filters as per the per-commit config file.

##### Actual Behavior

pre-commit runs ansible-lint on the whole repository.

**Comment by webknjaz** [comment]
This is mandatory for `ansible-lint` to work correctly. It mustn't be changed, otherwise `ansible-lint` won't understand the whole context of the relationships between files in the project which will inevitably lead to committing broken changes.

**Comment by MAC-R0ch3** [comment]
Thanks @webknjaz!

**Comment by autra** [comment]
> This is mandatory for `ansible-lint` to work correctly. It mustn't be changed, otherwise `ansible-lint` won't understand the whole context of the relationships between files in the project which will inevitably lead to committing broken changes.

I'd argue that a lot of errors still should not get reported in this case. For instance, yaml[truthy] or name[casing] for unchanged files. This would make incremental refacto of the codebase much easier.

Context: I inherit a big ansible codebase and I'd like to reformat a couple of files at a time, not the entire codebase.
