### ISSUE TITLE
exclude_path with either globbing or regexes to exclude stuff like roles/*/templates/*

### ISSUE THREAD

**Issue by flamein** [ansible-community/ansible-lint#322]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```
ansible --version
ansible 2.4.2.0
ansible-lint --version
ansible-lint 3.4.19
```

- ansible installation method: OS package
- ansible-lint installation method: OS package

# Desired Behaviour
It would be awesome if we could exclude paths from config file using either regexes or globs.
In a large setup it's impossible to keep adding full paths to the config.

**Comment by flamein** [comment]
hold on, this might be possible from pre-commit, which would solve my immediate issue

**Comment by ssbarnea** [comment]
@flamein Can you please provide mo info on your problem as I encountered something very similar, where ansible-lint seems to report some missing template files but only when called as a pre-commit hook, not when run standalone.

**Comment by g1ps** [comment]
Here's a solution that works for now:
```
# Plain search. All .yml files starting with a in the current dir.
ansible-lint $(find a.*.yml)

# With regex.
ansible-lint $(find -regex ".*a.*.yml")
```
You can use all of the facilities of `find` to limit what's checked, so
```
# Limit to the current directory. The example above will descend into /roles.
ansible-lint -v $(find . -maxdepth 1 -regex ".*a.*.yml")
```
Ranges:
```
# All .yml files starting with a, b, c, d.
ansible-lint $(find . -maxdepth 1 -regex ".*[a-d].*.yml")

## All .yml files starting with prefixa, prefixb, etc.
ansible-lint $(find . -maxdepth 1 -regex ".*prefix[a-d].*.yml")
```
Run `find` separately to refine your selection. Use `-v` on `ansible-lint` to see what it's actually checking. Use backticks or `$(...)` as you prefer.

Have fun.

**Comment by ssbarnea** [comment]
While the file type detection from 4.2 makes it less problematic is still annoying to get warnings about failure to load some files.

We still need to decide which path to take: globs vs regex, as they are kinda exclusive. I am inclined to go for globs because these would be backwards compatible.

**Comment by ssbarnea** [comment]
Recent changes made this bug irrelevant.

**Comment by zyphermonkey** [comment]
> Recent changes made this bug irrelevant.

Do you happen to know what version these changes were released in?

We're using https://quay.io/repository/ansible/toolset and the ansible-lint version in there is currently stuck at 5.0.12 and on that version globs don't appear to be working for `exclude_paths`.

**Comment by williamhanseneric** [comment]
There is a valid use case for this, i.e. I want to exclude everything in the ./roles folder except ./roles/local_roles

The --offline parameter doesn't work if you you want to work with the remote roles using "-g -f -r ./roles/requirements" and they exists locally in your project.
