### ISSUE TITLE
Warning/Error for unencrypted vaults on pre-commit 

### ISSUE THREAD

**Issue by f3rdy** [ansible-community/ansible-lint#417]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

any

# Desired Behaviour

I've had occurrences when I accidental checked in temporarily unencrypted vaults into git leading to effort on re-generating passwords and so on. In conjunction with the pre-commit package, it would be interesting to have ansible-lint show error or warning signs on unencrypted vault files before commit. 

What do you think?

**Comment by IamTheFij** [comment]
I've created the following pre-commit hook for exactly this: https://github.com/iamthefij/ansible-pre-commit

I'm happy to add it here, if there is any desire from the maintainers.

**Comment by ssbarnea** [comment]
Closing as I see it outside the scope of the linter but I would review a pull-request if proposed.
