### ISSUE TITLE
Feature request: Check for redundant boolean expressions in when clauses

### ISSUE THREAD

**Issue by mcandre** [ansible-community/ansible-lint#423]
Inline Python sections such as `when` clauses can feature some gnarly code. For example, users may say `when: (1 + 1 == 2) == True` rather than `when: 1 + 1 == 2`.

If we were dealing with ordinary .PY[W] files, then we could simply scan using Python linters. But here we have Ansible configuration files. Can we think of some ways to lint inline Python code with additional checks, such as regular Python linters would catch?

**Comment by webknjaz** [comment]
@mcandre it's not Python expressions, these are Jinja2 expressions, which have extended syntax so Python linters wouldn't work.
http://jinja.pocoo.org/docs/2.10/templates/#expressions

The idea is good though.

**Comment by webknjaz** [comment]
This is the only thing that I've found mentioning linting Jinja2 but it seems that the only validation it does is whether it compiles: https://pypi.org/project/mistral-lint/#e103-e104-e105-expressions.

If you wish to start digging into it, probably the best place to start is jinja's own lexer: https://github.com/pallets/jinja/blob/master/jinja2/lexer.py

Also, I've done some further research and it seems that @missyjcat has built some linting for JS-reimplementation of Jinja2 (Nunjucks JS) in past but it doesn't look that there's some prior art available open source:
https://www.vikingcodeschool.com/posts/jessica-chan-web-engineer-taking-on-your-first-big-project
https://medium.com/@Pinterest_Engineering/how-we-switched-our-template-rendering-engine-to-react-a799a3d540b0#521d

**Comment by webknjaz** [comment]
There's projects like
* https://github.com/motet-a/jinjalint
* https://github.com/drm/jinja2-lint

But they only lint non-expression parts of templates. The first one could be useful to lint jinja2 templates (which is also useful in scope of ansible-lint but is a separate problem).

There's literally nothing on the Internet for checking the expressions.

**Comment by mcandre** [comment]
Well, I'm excited to learn that the expressions are Jinja rather than Python!

Hmm, maybe we could just convince jinjalint or jinja2-lint to add this rule

**Comment by webknjaz** [comment]
I think you'd need to write your own code rather than using those tools. You'd need to rewrite smth like https://github.com/missyjcat/nunjucks-extension/blob/master/LinterExtension.js in Python...

**Comment by ssbarnea** [comment]
Closing as I do not see it ever being implemented, but I will review a PR if raised.
