### ISSUE TITLE
ansible-lint should include checking jinja2 templates

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#441]
# Issue Type
- Feature request

# Desired Behaviour

Many bugs with Ansible are inside Jinja2 templates and we need to lint them whenever they are embedded in ansible YAML code or stored separately with `.j2` extension.

At https://github.com/openstack/tripleo-quickstart-extras/blob/master/ci-scripts/validate_jinja2.py we have a small jinja2 verifier that we would like to contribute to ansible-lint, making easier to reuse it instead of having to copy it on each repository.

Some could argue that jinja2 is not ansible but the reality is that this is about ansible-jinja2 flavour which is not pure jinja2, so ansible-lint woudl be the perfect place to host this, as a new feature.

**Comment by claco** [comment]
As an aside, would be nice it match would also go through vars folder files and defaults folde files, even README. In fact any file in the role. 

Doing code workarounds and hooks for this now. IF this is something people would be interested in, I'm up for a proposal and a PR of what I'm currently using.

**Comment by Slamdunk** [comment]
Hi, how can we help to land this feature?

**Comment by fractalawareness** [comment]
@claco can you share what kind of workarounds do you use please?

**Comment by ssbarnea** [comment]
Closing as ansible-syntax check does cover at least some parts of this. If anyone wants to add something more, I will be happy to review their pull-requests.
