### ISSUE TITLE
Refactor: rename any object builtin conflicts

### ISSUE THREAD

**Issue by awcrosby** [ansible-community/ansible-lint#469]
For example, rename `file` in `matchtasks(self, file, text)`

**Comment by ssbarnea** [comment]
While I fully support the move and already made several changes in this areas, I am afraid that `file` is no longer a build-in.

```
 import builtins
>>> 'file' in dir(builtins)
False
```

One that I recently addressed was [type -> kind](https://github.com/pycontribs/meta/blob/master/doc/python-keyword-aliases.md).

Please add comment if you find others and also suggest alias to be used.
