### ISSUE TITLE
Error code when calling “ansible-lint *.yml”, for a .yml that is not a playbook structure

### ISSUE THREAD

**Issue by awcrosby** [ansible-community/ansible-lint#493]
Currently if a user tries to lint a .yml file, ansible-lint assumes it is a playbook and then outputs any linter issues. If a the .yml file is actually a tasks file such as `tasks/main.yml`, ansible-lint outputs no issues and the user likely thinks the file was linted succesfully. Discussed in #488.

Proposal when calling `ansible-lint *.yml` to check if the format is indeed a playbook format versus tasks file format, and exit with an error code if not a playbook.

**Comment by varac** [comment]
I think https://github.com/varac/ansible-lint-testrepo is a good example of this behaviour.
