### ISSUE TITLE
Support toggling noqa for spans of lines

### ISSUE THREAD

**Issue by eigengrau** [ansible-community/ansible-lint#586]
# Issue Type
- Feature request

# Desired Behaviour
Currently, for line-based rules, `noqa` must be present on the very line it applies to. This is inconvenient, e.g. because:

- adding `noqa` in-line can violate yamllint line-length rules
- comments can not be used in multi-line strings

It would be convenient if ansible-lint were to offer a way to disable certain line-based rules for a designated span of lines. E.g., like yamllint, we could declare the start and end of a block to which some rule exclusion applies:

```
# ansible-lint start noqa 206
…
# ansible-lint stop noqa 206
```

Alternatively, some of these use-cases might also be covered by #545.

**Comment by abeluck** [comment]
Another use case:

qa rule 201 - trailing spaces

We have a case where we use yaml block scalars to contain multi line strings that require trailing whitespace.

**Comment by ssbarnea** [comment]
Closing because it is not technically feasible to implement. I would rather find far easier to implement a list of specific errors to ignore inside config file than adding this.
