### ISSUE TITLE
add auto-formatter like black for ansible-lint code-base

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#619]
# Issue Type
- Feature request

# Desired Behaviour

Instead of wasting precious time debating about code formatting/style in reviews we should adopt a code-formatter like black and integrate it with code linting.

There are 3 well known such tools for python: [autopep8](https://github.com/hhatto/autopep8), [yapf](https://pypi.org/project/yapf/#description) and [black](https://github.com/psf/black).

I am proposing black because that is the newest one and officially supported by PSF. I seen a trend in the last ~18 months, more and more projects are adopting or switching to it from others. 

The other two are quite old and prone to signifiant problems like lacking idempotence or performance (yapf).

We successfully [swithed from yapf to black on ansible-molecule](https://github.com/ansible/molecule/pull/2152) back in August without any problems.  I can say that this helped bring down the number of open reviews.

Feel free to upvote/downvote on the proposal as I think it would be a good idea to get an idea about what other contributers think.

**Comment by webknjaz** [comment]
Well, you know how I feel about black. IMO there's no **really good** autoformatting helper nowadays.

> officially supported by PSF

This is totally misleading perception. It's not like they recommend everyone to use it. They just host the repo.

**Comment by webknjaz** [comment]
Adding a *linter* would be good, though.

**Comment by webknjaz** [comment]
Counter proposal: use a really good linter suite — https://wemake-python-stylegui.de/en/latest/pages/api/index.html#philosophy.

**Comment by ssbarnea** [comment]
As I recently wasted a log of time on reviews around with "style" comments, I think the we would benefit more from outsource that activity to black. At least this will not introduce more subjectivity and will apply same rules for all PRs.

@awcrosby and @albinvass please add your thumb-up or thumb-down on this change request as I see we have a standstill.

I am really happy to see that @willthames also supports the move and I am sure that the number of changes made by black will be very low, since we already implemented lots of other changes. My impression is that all flake8, pylint, isort are embracing black and play much better one with another then in previous years.

In order to avoid extra reformatting I propose to adopt black in relax mode: with quote style enforcement disabled and using our own max-line 100 instead of its 88. I would personally prefer to go pure-black, w/o any exceptions but doing this in one go introduces too many changes (or debates), so better to avoid it.

**Comment by webknjaz** [comment]
I'm still against black and pro linter.
