### ISSUE TITLE
Bug: ansible-galaxy generates files that fail ansible-lint

### ISSUE THREAD

**Issue by asfarley** [ansible-community/ansible-lint#673]
# Issue Type
Possible bug: ansible-galaxy generated 'role' files fail ansible-lint.

# Ansible and Ansible Lint details

ansible 2.9.4
ansible-lint 3.4.20

Both installed via OK package

# Desired Behaviour

I expect that a vanilla directory-structure generated by ansible-galaxy would pass ansible-lint.

# Actual Behaviour (Bug report only)
I just created a fresh role. Running ansible-lint on a playbook containing this role gives:

`[ANSIBLE0002] Trailing whitespace`

I have not modified this file, so ansible-lint is complaining about files generated by ansible-galaxy.

**Comment by asfarley** [comment]
Specifically, it's the /meta/main.yml file which contained trailing whitespace.

**Comment by ssbarnea** [comment]
This is not an ansible-lint issue, feel free to fix this in galaxy but keep in mind that code generators do not guarantee that expanded result is passing linting. Another example is the fact that you must complete some fields after that.
