### ISSUE TITLE
New type of match function for custom linting rules that is only executed once for entire playbook 

### ISSUE THREAD

**Issue by renskewierda** [ansible-community/ansible-lint#674]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```
ansible --version
ansible 2.8.5
ansible-lint --version
ansible-lint 4.1.0
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour
I am working on a custom linting rule. In the ansible-lint documentation, the following two possibilities are mentioned for match functions to include in a custom linting rule:

match(self, file, line)
matchtask(self, file, task)

I was wondering if it would be possible to create a third type of match function, something like:

matchplaybook(self,playbook).

This could be used when you only want to call the function once, for the entire playbook, and not for every line of code or for a specific kind of task.

Use case: I have written a custom linting rule to check for the values of certain variables in inventory files. Since ansible-lint does not include inventory files, I have included a look up in the match function that gets inventory files and searches for particular variable values in there. But since the match function is executed for every line of code, the same error in an inventory now appears as many times as there are lines of code in a playbook so I get a lot of duplicate alerts.

If it would be possible to define a kind of match function that is only executed once, then the look up for variables in inventory files would only happen once and I would not get duplicate results.

Another solution would be to add a config setting to include inventory files in ansible-lint instead of only playbooks.

I'm curious to know whether you would be interested in adding one of these features (either a "match playbook" type of function or making it possible to include inventory files in an ansible-lint check).

**Comment by renskewierda** [comment]
Any updates on this?

**Comment by ssbarnea** [comment]
Lots of things changed since, look at https://github.com/ansible-community/ansible-lint/blob/master/src/ansiblelint/_internal/rules.py#L56-L60
