### ISSUE TITLE
utils.is_playbook(filename) crashes on some yaml files

### ISSUE THREAD

**Issue by infothrill** [ansible-community/ansible-lint#687]
# Issue Type
- Bug report

# Ansible Lint details

```
ansible-lint 4.2.0
```

- ansible-lint installation method: pip and homebrew

# Desired Behaviour

When running the `ansible-lint` command barebones, it will walk the filesystem in the current working directory and detect playbooks to be linted/verified. For this purpose, a utility function dubbed `is_playbook(filename)` is defined at https://github.com/ansible/ansible-lint/blob/master/lib/ansiblelint/utils.py#L730
The function implements, among other things, checks for certain structures to be expected in ansible playbooks. These checks are supposed to return one of True|False to allow further processing logic to proceed. For non playbook files (that are valid yaml files), the expected behaviour is to return False for non playbook files.

# Actual Behaviour

The function crashes for certain types of yaml inputs like
```
cat requirements.yml
---
- username.galaxyrole
```
Actual error:
```
ansible-lint requirements.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/ansible-lint/4.2.0_1/libexec/lib/python3.8/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/usr/local/Cellar/ansible-lint/4.2.0_1/libexec/lib/python3.8/site-packages/ansiblelint/__init__.py", line 267, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/usr/local/Cellar/ansible-lint/4.2.0_1/libexec/lib/python3.8/site-packages/ansiblelint/utils.py", line 161, in find_children
    items = _playbook_items(playbook_ds)
  File "/usr/local/Cellar/ansible-lint/4.2.0_1/libexec/lib/python3.8/site-packages/ansiblelint/utils.py", line 146, in _playbook_items
    return [item for play in pb_data for item in play.items()]
  File "/usr/local/Cellar/ansible-lint/4.2.0_1/libexec/lib/python3.8/site-packages/ansiblelint/utils.py", line 146, in <listcomp>
    return [item for play in pb_data for item in play.items()]
AttributeError: 'AnsibleUnicode' object has no attribute 'items'
```

# Background
It is common to have a file called `requirements.yml` in ansible projects to reference external roles processed through the `ansible-galaxy` command. In particular, in my case, a tool dubbed `molecule` is used to run tests for ansible roles. To accommodate the test flow, external dependencies are defined in a `requirements.yml` file. However, during the test run, `ansible-lint` is being called with no specific input (e.g. current working directory), tests the file `requirements.yml` for errors and crashes, failing to provide valid feedback on the actual playbooks found in subdirectories.

# Workaround
An immediate workaround for the example provided is to patch the `requirements.yml` file to reference the external role dependency using a more canonical format (adding `src: `):

```
cat requirements.yml
---
- src: username.galaxyrole
```
However, many (even though little) code changes may need to be done for this and therefore may warrant a review of the affected `is_playbook()` function.

**Comment by ssbarnea** [comment]
This bug was fixed on master branch.
