### ISSUE TITLE
proposal: Adopt and document smart CI-testing matrix

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#699]
At this moment ansible-lint is testing using 3 different CI/CD systems with a huge number of jobs (over 100) while most of them are very-unlikely to cover real-world use cases, being only the results of an exploding all permutations found so far. 

This not only produces a considerable resource loading and delays on getting results, but also imposed additional maintenance costs with managing these jobs.

This proposal is about cherry-picking only these configurations that are most likely to be used by the users. With a more careful picking of combinations we can even provide a better practical coverage with far smaller number of jobs. For example, it can prove far more useful to test ansiblelint with default version of python shipped with multiple operating systems instead of trying to test all python versions on the same operating system, especially as some of these may not be even supported by the operating system vendor.

Variables in testing matrix:
* platforms: `centos-8`, `fedora-stable`, `ubuntu-bionic`, `macos-latest`
* python: `py36`, `py37`, maybe even `py38` as experimental
* ansible versions: `2.9`, `2.8`, `devel`
* jobs: simple like `linters`, `docs` or complex like unit/functional with the main difference being that the simple ones are used for development, and they do not need to have the same requirements.

Proposed matrix for simple jobs (2x2=4):
* linters + docs tested only with centos-8 and py36
* linters + docs tested only with and macOS and py36

Proposed matrix for complex jobs (5x3=15)
* centos-8-py36-ansible2x
* ubuntu-xenial-py36-ansible2x
* fedora-stable-py37-ansible-2x
* macos-latest-py36-ansible-2x

This list is missing py38 and we may want to make few adjustments to it but the entire idea is that we should try to test only combinations that are high-likely to happen in practice, or those that are going to be popular. The list is not set in stone, and we would be able to adjust it based on needs, even temporary enabling new jobs if we discover that this is needed.

There are also few other aspects related to this which are currently not covered and maybe we should cover for them: testing the installation of the package: to system, to virtualenv, to user site packages, installation as editable, installation from git, sdist or wheel, installation with various versions of python packaging tools lower/upper constraints. The reality is that these are known to caused lots of problems, but we do not really test them. Obviously that it would make no sense to create full jobs for each of these variations, but we could easily find ways to perform basic sanity checks of these within the other jobs that run on the same platforms. 

@awcrosby @gundalow @webknjaz I am looking forward to receive feedback on this proposal

[![](https://api.gh-polls.com/poll/01E4ZXT20X033Z16HPGQ86VADZ/yes)](https://api.gh-polls.com/poll/01E4ZXT20X033Z16HPGQ86VADZ/yes/vote)
[![](https://api.gh-polls.com/poll/01E4ZXT20X033Z16HPGQ86VADZ/no)](https://api.gh-polls.com/poll/01E4ZXT20X033Z16HPGQ86VADZ/no/vote)

**Comment by webknjaz** [comment]
Not sure about removing envs, but it'd be nice to have all those extra cases put in Zuul, I guess. Dropping Python 2 is good as discussed on Freenode.
