### ISSUE TITLE
Reduce McCabe complexity

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-lint#744]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

N/A

# Desired Behaviour

The source code should be refactored so that flake8 doesn't fail.

# Actual Behaviour (Bug report only)

* [ ] `lib/ansiblelint/__main__.py`:32:1: C901 'main' is too complex (13) (@dpendolino -- #931)
* [x] ~`lib/ansiblelint/utils.py`:229`:1: C901 '_taskshandlers_children' is too complex (12)~ (#903 / #862)
* [ ] `lib/ansiblelint/utils.py`:413:1: C901 'normalize_task_v1' is too complex (11)
* [ ] `lib/ansiblelint/utils.py`:802:1: C901 'get_playbooks_and_roles' is too complex (17)
* [x] ~`lib/ansiblelint/rules/MetaMainHasInfoRule.py`:24:5: C901 'MetaMainHasInfoRule.matchplay' is too complex (13)~

To see the errors and fix them, one needs to remove `C901` ignores from the `per-file-ignores` setting in the `.flake8` config file and from the source code (noqa).

**Comment by webknjaz** [comment]
@dpendolino if you want, you could take some of the subtasks here. While it's assigned to @ssbarnea I believe he hasn't had time to start solving this. OTOH since there's complexity in several places, the fixes may be submitted as separate PRs. Just comment here to announce your intent to work on something specific to avoid race conditions...

**Comment by ssbarnea** [comment]
I removed myself as I do not expect to work on it. Indeed, there is a set of areas where it should be easy for anyone to make small contributions: increase typing coverage, one function at a time, removing QA skips like mccabe or docstrings.

Hint: do not try to fix too much at once, small batches are better than big.

**Comment by webknjaz** [comment]
@dpendolino I assigned you here, try to select one function to improve for starters.

@tohtohro this may be great for you too, it's a relatively simple refactoring task. Since there's 3 places still needing fixing, you may take one of those. Just announce which one.

**Comment by dpendolino** [comment]
@webknjaz I'll take the `main` complexity subtask. PR incoming =]
