### ISSUE TITLE
RFP: standardize in-repo custom rules locations

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#755]
##### Summary
In order to make it easier for people to write custom rules inside their repositories, I would like to propose including a new folder in the default search path of the linter: `{REPO}/.config/ansiblelint/rules`. For backwards compatibility we would keep the existing default, the new path being added after it.

This is following the XDG config use-pattern and we can even use HOME when a repository is not detected. It avoids cluttering the repo root folder and is easy to expand in the future.

##### Issue Type

- Feature Idea

##### Additional Information

For example I already implemented a similar feature in molecule which loads configuration from `{REPO|HOME}/.config/molecule/config.yml`. That pattern make it easy for users to understand that a repo-config takes precedence over a user-config.

Reference: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by webknjaz** [comment]
Dunno about repo-local it might be a good idea. Inviting @cans, he may be interested in discussing this too.

> This is following the XDG config use-pattern and we can even use HOME when a repository is not detected. It avoids cluttering the repo root folder and is easy to expand in the future.

The reason Ansible itself doesn't do this is security considerations. So I'd say no relying on XDG env vars.

**Comment by ericsysmin** [comment]
Following for sure, because this would simplify my repository layout much better than a bunch of `.lint_config` files

**Comment by ssbarnea** [comment]
@ericsysmin I raised this because I seen other tool authors doing the same move, mainly people complained about getting too many config files inside the root of the repository.

**Comment by ssbarnea** [comment]
Closing as not being a priority but a pull request will be welcomed.
