### ISSUE TITLE
Auto-detect reports "Unknown file type" for all playbooks even in examples directory

### ISSUE THREAD

**Issue by luiseterc** [ansible-community/ansible-lint#808]
##### Summary

When calling ansible-lint without arguments (auto-detect mode) the function is_playbook returns False for all the playbooks (yaml or yml) found in the current folder.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible --version
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible;/etc/ansible/roles']
  ansible python module location = /data/DEV/virtualenvs/ansible299/lib/python3.6/site-packages/ansible
  executable location = /data/DEV/virtualenvs/ansible299/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]

ansible-lint --version
ansible-lint 4.3.0a2.dev25+geca19dd
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

Tested by cloning ansible-lint repo (master branch), cd into examples directory and called `ansible-lint`:

```
DEBUG    Logging initialized to level 0
DEBUG    Options: Namespace(colored=True, config_file=None, display_relative_path=True, exclude_paths=[], format='plain', listrules=False, listtags=False, parseable=False, parseable_severity=False, playbook=[], quiet=False, rulesdir=[], skip_list=[], tags=[], use_default_rules=False, verbosity=0)
INFO     Discovering files to lint: git ls-files *.yaml *.yml
INFO     Unknown file type: example.yml
INFO     Unknown file type: handlers/y.yml
INFO     Unknown file type: include.yml
INFO     Unknown file type: lineno.yml
INFO     Unknown file type: lots_of_warnings.yml
INFO     Unknown file type: nomatches.yml
INFO     Unknown file type: play.yml
INFO     Unknown file type: roles/bobbins/tasks/main.yml
INFO     Unknown file type: roles/morecomplex/tasks/main.yml
INFO     Unknown file type: tasks/x.yml
INFO     Unknown file type: unicode.yml
INFO     Found roles: roles/bobbins roles/morecomplex
INFO     Found playbooks: 
DEBUG    Examining roles/bobbins/tasks/main.yml of type tasks
DEBUG    Examining roles/morecomplex/tasks/main.yml of type tasks
DEBUG    Examining roles/morecomplex/handlers/main.yml of type handlers
```

##### Desired Behaviour

I should be able to find playbooks which actually contains tasks, hosts or other keywords included in the playbook_keys dict.

**Comment by GogineniManojkumar** [comment]
I also facing the same issue. do we have any solution for this? @luiseterc

**Comment by webknjaz** [comment]
@ssbarnea ^

**Comment by webknjaz** [comment]
@luiseterc @GogineniManojkumar Any chance you could send a PR with a pytest test reproducing this per https://github.com/ansible/ansible-lint/issues/725?

**Comment by misilot** [comment]
Is there a way to force including files that are of "Unknown file type" that are actually playbooks?

**Comment by ssbarnea** [comment]
@misilot I would bother less about logging, it is a known but that it reports as unknown more than needed, but it really lints them. Very easy to verify: just add something that you know to cause a linting issue inside.

**Comment by misilot** [comment]
@ssbarnea I don't think it does lint them. I just opened on the files and noticed I didn't have a task named so I ran ```ansible-lint file.yml``` explicitly and it did return ```[502] All tasks should be named
file.yml:14``` as expected. When I just run ```ansible-lint``` from the main directory (same location where file.yml is) I do not get the 502 reported.

**Comment by PandaWill** [comment]
@misilot I am still using this as our workaround:
```
 ansible-lint $(grep -Pl "(- name:.*|import_playbook:)" *.yml)
```

**Comment by ssbarnea** [comment]
Yep, files in root repository will not be picked as playbook for now, as they do not follow https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html guidelines (ansible itself has no guidelines regarding layout). Putting random files at repository root makes impossible to guess their types so only those hosted under folders containing "playbook" word will be picked.

There are no particular plans to change this behavior for now but if someone creates a PR to improve the logic it will be considered. For example it could prove useful to add a configuration item that marks the folders or patterns for folders that must contain playbooks (implicit would likely be a list with just "playbook"). Now that part is hardcoded but it will pick variations like "test-playbooks" folders if you have any.

**Comment by misilot** [comment]
Thanks @ssbarnea for the info. I was using ansible to run over my complete "ansible" directory setup similar to what is described at https://docs.ansible.com/ansible/latest/user_guide/sample_setup.html#alternative-directory-layout.

Thank you @PandaWill for that snippet.
