### ISSUE TITLE
Set up bors-ng based merge gating

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-lint#820]
##### Summary

I'd like to integrate [bors-ng] as a gating system. Most folks
agree that having a robot do merges is preferrable over human-
driven merges.

I know that Zuul also supports this but it doesn't support
checking statuses from other CIs so it's a no-go atm. This does
not mean that Zuul is not going to be used at all. It's just that
it's gating subsystem will remain disabled (just as it is now).

The workflow is pretty straightforward: anybody with review
privileges will be able to comment with things like `bors r+`
to make bors-ng try merging it in. It ensures that anything
that gets into master always has a green CI. It also tries to
merge a few things an a time in order to find if several parallel
PRs don't conflict and it also reduces the CI resources used.

Last but not least, it'll allow us to implement #815 even more
smoothly. And permanent reviewers can also delegate the review
privilege to other people on per-PR basis when needed (using
[bors commands]).

##### Issue Type

- Feature Idea

##### Additional Information

N/A

[bors commands]: https://bors.tech/documentation/
[bors-ng]: https://bors.tech/

**Comment by ssbarnea** [comment]
@pabelanger Do you think we have any chance to make zuul consider other CI results before deciding to merge a gate or not really? If we can do that we can avoid setting yet another system to an already very complex mix of 4 different CI systems.

**Comment by webknjaz** [comment]
@ssbarnea implementing it manually is harder than you think because you have to check a few APIs simultaneously and also Zuul doesn't support some of the other features I mentioned AFAIK. bors-ng is better integrated with GH a overall. I don't think it'll add much complexity really.

**Comment by pabelanger** [comment]
Checks from other CI systems are not an issue. As long as it is reporting to the API of github, zuul can query it.

**Comment by webknjaz** [comment]
@pabelanger so can it also test multiple PR branches in batches?

**Comment by pabelanger** [comment]
Could you explain what 'multiple PR branches in batches' means?  1 single PR against all the project branches or multiple PRs to multiple branches?

**Comment by ssbarnea** [comment]
@webknjaz Yes Zuul can gate multiple changes quite well. Still, for ansible-lint that is not really a real requirement, its jobs run <5min each and we do not have so many changes anyway. For bigger projects is very useful.

**Comment by webknjaz** [comment]
@pabelanger if people comment `bors r+` in multiple PRs around the same time, it'll merge them all into a temporary branch with master, test that and only then will fast-forward master to that commit. It'll also try to bisect bad PRs if that fails.

**Comment by ssbarnea** [comment]
I think that the real deal-breaker features needed for ansible-lint are: be able to merge PRs only when they have at least one passed review and all github checks (jobs) passed. If Zuul can do that today, we can avoid enabling another tool.

**Comment by pabelanger** [comment]
i would encourage you to read https://zuul-ci.org/docs/zuul/discussion/gating.html to understand how gating works in zuul. Zuul uses dependant pipeline managers to do parallel speculative testing. There is a good example of how that works with a PR.

**Comment by webknjaz** [comment]
@ssbarnea FWIW bors looks cleaner atm and I don't like the band-aid solution with a waiting job. Also, I want it for its features (like what I've described earlier).
Plus I like that many people I know personally have a very positive feedback about bors.

**Comment by TristanCacqueray** [comment]
@webknjaz what band-aid solution are you refering to (support for multiple PRs is one of Zuul's core feature) ?

Bors looks neat, could you show some project's PR using the `bors r+` comment?

**Comment by webknjaz** [comment]
@TristanCacqueray band-aid == @ssbarnea's suggestion to have a job that does polling of the checks and statuses. Also, AFAIK Zuul doesn't have a very user-friendly dashboard for this (at least what I saw was quite poor and didn't have any controls).


I couldn't remember the specific repos (only the people who introduced me to bors) but here's some examples I've found: https://github.com/rust-analyzer/rust-analyzer/pull/4796#issue-431134135 + https://github.com/wasmerio/wasmer/pull/1469#issuecomment-640495110.

I haven't seen many people using commands other than `bors r+` because it's the main one so I don't consider it hard to learn (unless one wants to use other commands, of course).

Here's bors' own dashboard https://app.bors.tech/repositories/3 — you need to log in via GitHub to see it. It's a read-only view with a list of the PRs.

**Comment by ssbarnea** [comment]
Yep, I would be curious to see which mainstream projects are using it. I wasn't able to find any reference user stories around. Without seeing that I am afraid that bors-ng itself may be labeled as a band-aid.

I am really concerned about adding more complexity to the development workflow of ansible-lint, I think that the fact that we have 4 different CI/CD systems is already unreasonable. My previous proposalals of reducing the number of CI/CD systems where refused. I reached a point where I got the impression that adding more stuff that can break was by design, so we can have more gears that can break. Ansible-lint project should not be used as a playground for testing various testing tools (services,bots,...).

PS. By mainstream, I mean projects with more github stars than ansible-lint itself.

**Comment by webknjaz** [comment]
> PS. By mainstream, I mean projects with more github stars than ansible-lint itself.

Both projects I linked above have move starts.

As for adding more complexity, I'd say that learning Zuul adds more complexity in my eyes. Way more than borg.

**Comment by pabelanger** [comment]
I would prefer we work to understand how zuul cannot work, and address that. So far we have a large amount of ansible projects now using it, like molecule, ansible-runner, receptor and collections. https://dashboard.zuul.ansible.com/t/ansible/projects

As for polling, zuul does not need to do that, please see https://zuul-ci.org/docs/zuul/discussion/github-checks-api.html for more information on the github checks api we have access to now. It https://zuul-ci.org/docs/zuul/reference/drivers/github.html#requirements-configuration is more details on how pipelines can be configured with requirements.

Also, I _think_ the checks could also be managed at a branch protection level, meaning zuul would not enqueue the change into the pipeline, until all checks in branch protection passed. But, I need to confirm this.

**Comment by ssbarnea** [comment]
In fact we can implement desired behavior with only few project setting clicks, without any extra bots/apps:

* require min 1 review before merge
* require passing `zuul-check`, `travis', ... before merge
* limit merge capability to "ansible-zuul" user

Even if someone adds the "gate" label before reviews are made or all the jobs are passing, they will not be able to merge anything.

This means that we will use a similar project like other ansible projects and avoid reinventing the wheel.

**Comment by pabelanger** [comment]
> In fact we can implement desired behavior with only few project setting clicks, without any extra bots/apps:
> 
> * require min 1 review before merge
> * require passing `zuul-check`, `travis', ... before merge
> * limit merge capability to "ansible-zuul" user
> 
> Even if someone adds the "gate" label before reviews are made or all the jobs are passing, they will not be able to merge anything.
> 
> This means that we will use a similar project like other ansible projects and avoid reinventing the wheel.

yes, this all should work today. And we can test with say molecule to confirm

**Comment by TristanCacqueray** [comment]
Zuul respects project's branch protection rules and you can configure Status or Check gate requirement if you want.

The Bors examples does not show cross PR dependencies nor bad PR bisect. I'd be interested to see how Bors achieve that. Is this something available through the dashboard interface?

**Comment by webknjaz** [comment]
@TristanCacqueray I don't know the answer to that. It got to me mostly in the form of tribal knowledge. AFAIK if there's 5 branches merged into a temporary branch and the testing fails, it gets removed and those branches are divided into two groups (3+2) and each of groups gets merged into a temp branch separately and if it succeeds, it gets into master, if it doesn't, the bisecting goes on to identify which branches result in a green merge and which ones are red.

Also, I'm not aware of any dependencies support. It's plain simple. If multiple PRs are approved around the same time — they all are tested together in an attempt to get them into master.

**Comment by TristanCacqueray** [comment]
@webknjaz thank you for the interesting details. If I understand correctly, Zuul would either reports a merge or test failure when two PRs are incompatible. It would be good to see and compare how Bors reports such conflicts.

Also it seems like using temporary branch would prevent Bors from working across different projects.

**Comment by webknjaz** [comment]
@TristanCacqueray if you mean forks, then no. It works with them. But there's no feature of having cross-project deps. It's basically a merging orchestrator that sits on top of existing CIs.

**Comment by albinvass** [comment]
> As for adding more complexity, I'd say that learning Zuul adds more complexity in my eyes. Way more than borg.

I'm not sure what the perceived complexity of zuul is.
Bors seem to need more input from the user (adding a comment) instead of relying on things that already exist (approving the change).

**Comment by ssbarnea** [comment]
Bit on the funny side, I had a big laugh first time I read [Bors](https://en.wikipedia.org/wiki/Bor%C8%99_%28bran%29) as that is a fermented liquid from which sour soups are made in eastern Europe, quite a tasty one (for those used to lactic fermentation).
