### ISSUE TITLE
None list item crashes ansible-lint

### ISSUE THREAD

**Issue by trevorpeacock** [ansible-community/ansible-lint#849]
##### Summary
ansible-lint crashes when processing an empty task list item.

I found this in our repo where someone thought they had commented out a task:
```yaml
- #debug:
  #  msg: Hello!
```

In effect the file contains
```yaml
-
```

problem also occurs with
```yaml
-
- debug:
    msg: Hello!
```

They all appear to be valid YAML, and are all handled (ignored) by ansible.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details
```console
(venv) user@test:~/ansible$ pip install git+https://github.com/ansible/ansible-lint.git
Collecting git+https://github.com/ansible/ansible-lint.git

...

Successfully installed MarkupSafe-1...
(venv) user@test:~/ansible$ which ansible-lint
/home/user/ansible/venv/bin/ansible-lint
(venv) user@test:~/ansible$ ansible-lint --version
ansible-lint 4.3.0a2.dev64+g5e16103
```

- ansible-lint installation method: discovered via OS package: apt on ubuntu, verified on latest devel version from git

##### STEPS TO REPRODUCE

create a file with one of the examples above, and pass it to ansible-lint.
```python-traceback
(venv) user@test:~/ansible$ cat test.yml 
 - #debug:
   #  msg: Hello!

(venv) user@test:~/ansible$ ansible-lint test.yml -vvv
DEBUG    Logging initialized to level 10
DEBUG    Options: Namespace(colored=True, config_file=None, display_relative_path=True, exclude_paths=[], format='plain', listrules=False, listtags=False, parseable=False, parseable_severity=False, playbook=['test.yml'], quiet=False, rulesdir=[], skip_list=[], tags=[], use_default_rules=False, verbosity=3)
DEBUG    Loading rules from /home/user/ansible/venv/lib/python3.8/site-packages/ansiblelint/rules
Traceback (most recent call last):
  File "/home/user/ansible/venv/bin/ansible-lint", line 8, in <module>
    sys.exit(main())
  File "/home/user/ansible/venv/lib/python3.8/site-packages/ansiblelint/__main__.py", line 116, in main
    matches.extend(runner.run())
  File "/home/user/ansible/venv/lib/python3.8/site-packages/ansiblelint/runner.py", line 73, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/home/user/ansible/venv/lib/python3.8/site-packages/ansiblelint/utils.py", line 159, in find_children
    items = _playbook_items(playbook_ds)
  File "/home/user/ansible/venv/lib/python3.8/site-packages/ansiblelint/utils.py", line 134, in _playbook_items
    return [item for play in pb_data for item in play.items()]
  File "/home/user/ansible/venv/lib/python3.8/site-packages/ansiblelint/utils.py", line 134, in <listcomp>
    return [item for play in pb_data for item in play.items()]
AttributeError: 'NoneType' object has no attribute 'items'
```

##### Desired Behaviour
The examples provided are valid YAML, but do not make sense in the context of an ansible task/playbook. ansible-lint should at a minimum not crash, but ignore the item as ansible does.
ansible-lint should ideally identify the code examples provided as nonsensical ansible templates, and report a file and preferably an approx line number as for user to check.

##### Actual Behaviour
Method `_playbook_items` in `utils.py` attempts to iterate over a None in `pb_data` and ansible-lint produces a stacktrace. See output above.

output of `ansible-playbook --syntax-check playbook` (tested with play containing all three examples, ansible runs and reports no problems)
```console
user@test:~/ansible$ ansible-playbook -i ./test_hosts --syntax-check ./play.yml

playbook: ./ansible/site.yml
```

**Comment by ssbarnea** [comment]
The example gave by you is not valid Ansible, there is no such thing as an empty task.
```
ERROR! playbook entries must be either a valid play or an include statement
```

Still, I will keep this bug open because I do not think that we should give a stacktrace.

**Comment by widget** [comment]
I was going to raise a separate issue, but it might be related.  I get a similar crash with the input
```
---
..
```
A missing `.` gives:
```
Traceback (most recent call last):
  File "/home/widget/.local/share/virtualenvs/ansible-playbooks-7pvYrsZ2/bin/ansible-lint", line 8, in <module>
    sys.exit(main())
  File "/home/widget/.local/share/virtualenvs/ansible-playbooks-7pvYrsZ2/lib/python3.8/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/home/widget/.local/share/virtualenvs/ansible-playbooks-7pvYrsZ2/lib/python3.8/site-packages/ansiblelint/__init__.py", line 267, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/home/widget/.local/share/virtualenvs/ansible-playbooks-7pvYrsZ2/lib/python3.8/site-packages/ansiblelint/utils.py", line 161, in find_children
    items = _playbook_items(playbook_ds)
  File "/home/widget/.local/share/virtualenvs/ansible-playbooks-7pvYrsZ2/lib/python3.8/site-packages/ansiblelint/utils.py", line 146, in _playbook_items
    return [item for play in pb_data for item in play.items()]
  File "/home/widget/.local/share/virtualenvs/ansible-playbooks-7pvYrsZ2/lib/python3.8/site-packages/ansiblelint/utils.py", line 146, in <listcomp>
    return [item for play in pb_data for item in play.items()]
AttributeError: 'str' object has no attribute 'items'
```

**Comment by perlun** [comment]
> The example gave by you is not valid Ansible, there is no such thing as an empty task.

Empty tasks in a role is at least valid with Ansible 2.9.11. I can execute the playbook below without any errors:

```
$ ls -l
total 8
drwxr-xr-x 3 per per 4096 nov 26 15:52 roles
-rw-r--r-- 1 per per   33 nov 26 15:52 test.yml
$ cat test.yml 
- hosts: all
  roles:
    - test
$ cat roles/test/tasks/main.yml 
-
```

Perhaps a more normal use case would be to have an empty task and then some non-empty tasks in the same file. :slightly_smiling_face: But the above illustrates my point.

Anyway, I think a proper fix here would be to note that the item was a `NoneType` and raise a linter warning. There is little reason to write Ansible roles/playbooks like this, and we'd better reject it unless configured differently. WDYT @ssbarnea?
