### ISSUE TITLE
proposal: refactor AnsibleLintRule rules to ensure consistent type

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#922]
##### Summary
Due to historical reasons [AnsibleLintRule](https://github.com/ansible/ansible-lint/blob/master/lib/ansiblelint/rules/__init__.py) base class does not define methods that can be defined by rules, instead it does only define them as attributes and assign them None.

##### Issue Type

- Feature Idea

##### Additional Information

Any rule can implement these methods using its own arguments and return type, creating bugs, especially as these methods are called by the linter itself, not being really private methods of the rules.

The list of methods that need to be defined as empty in base class in order to assure the implementations use same arguments and return types:

* `match` - attribute ``None``
* `matchtask` - attribute ``None``
* `matchplay` - attribute ``None``

Methods already defined that return `List[Match]`
* `matchlines`
* `matchtasks`
* `matchyaml`

The returned values from these rules is also inconsistent and follows a mix of the following return types at this moment:

* `True` or `False` - meaning that the rule matches or not
* `List[]` - empty when no matches were found
* `List[Tuple(dict, str)]` - used by rules that can return multiple different errors.
* possible a variation of above (did not check all rules yet)

These tuples are a historical relic from the time when linter didn't use a Match object to identify an individual violation. IMHO, we would be better off if we migrate towards returning `List[Match]`, as it would make processing much easier and avoid lots of conditionals regarding how to process/format these.

Always returning a List would likely have no impact on current bool evaluations and also allow to directly loop over results without extra checks.

**Comment by webknjaz** [comment]
> The list of methods that need to be defined as empty in base class in order to assure the implementations use same arguments and return types:

A common way of specifying interfaces in Python is https://docs.python.org/3/library/abc.html. I suggest using it but being careful about applying the `@abstractmethod` decorator (as it makes such methods mandatory to implement).

**Comment by ssbarnea** [comment]
Yep, abstract does not make sense because is perfectly ok for rules to implement only some of the methods. A lot of branching (conditionals) would be avoided by having empty methods instead of null ones. Speed is no concern here.

**Comment by ssbarnea** [comment]
Done in master.
