### ISSUE TITLE
`rules` configuration from file is interpreted relative to the execution path rather than the path of the file

### ISSUE THREAD

**Issue by bendem** [ansible-community/ansible-lint#938]
##### Summary

With a configuration like this:
```yml
rules:
  - ./lints/
```
and a directory layout like this:
```
.ansible-lint
lints/
roles/java/tasks/main.yml
```

Executing `ansible-lint -c .ansible-lint roles/java` from the root directory works but executing `ansible-lint -c ../../.ansible-lint .` from `roles/java` breaks.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible --version
ansible 2.9.10
  config file = None
  configured module search path = ['/home/bendem/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/lib/python3.8/site-packages/ansible
  executable location = /home/bendem/.local/share/virtualenvs/ansible-gz-Hv99h/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

ansible-lint --version
ansible-lint 4.2.0
```

- ansible installation method: pip with pipenv
- ansible-lint installation method: pip with pipenv

##### OS / ENVIRONMENT
Ubuntu 20.04 in WSL1 in Windows 10 (1909)

##### STEPS TO REPRODUCE
See above

```console (paste below)
(ansible) ➜  repo-root git:(features/docker/maven-slim) ✗ ansible-lint -c .ansible-lint roles/java
roles/java/tasks/main.yml:7: [E9100] package tasks must use package_python_interpreter
(ansible) ➜  repo-root git:(features/docker/maven-slim) ✗ cd roles/java
(ansible) ➜  java git:(features/docker/maven-slim) ✗ ansible-lint -c ../../.ansible-lint .
```

##### Desired Behaviour
The path of the rules directory should be evalutated relative to the file that defines it, not the place where ansible-lint is executed

##### Actual Behaviour
Well, the reverse...

**Comment by ssbarnea** [comment]
Closing a there are no plans to fix but a pull-request would be welcomed.
